name: Run tests on PR creation
on: 
  push:
    branches:
      - tests
jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: maynard-io-public
          service_account_key: ${{ secrets.GCP_SA }}
          export_default_credentials: true
      -
        name: Setup Docker
        run: |
          # Build Container Locally for testing
          echo "Building kubernetes-cloud-mysql-backup..."
          docker build -t kubernetes-cloud-mysql-backup:test . 
          # Pull MySQL
          echo "Pulling mysql:5.7.32..."
          docker pull mysql:5.7.32
          # Create Docker Network
          echo "Creating Docker network..."
          docker network create --driver bridge backup-net
      -
        name: Setup Test Database
        run: |
          # Start MySQL Database
          echo "Starting MySQL Container..."
          docker run --name db-server -p 3306 --network backup-net -e MYSQL_ROOT_PASSWORD=letmein -d mysql:5.7.32
          # Wait for MySQL to Start. The MySQL container takes a long time to start
          echo "Waiting for MySQL Container to start..."
          sleep 90
          # Import Test DB
          echo "Importing test DB..."
          docker exec -i db-server mysql -u root -pletmein < tests/db/world.sql
      -
        name: Test GCP backup
        run: |
          # Perform database backup
          echo "Performing database backup..."
          docker run -e GCP_GCLOUD_AUTH=${{ secrets.GCP_SA }} -e GCP_BUCKET_BACKUP_PATH="/${{ github.sha }}" --env-file tests/configs/gcp.env --network backup-net kubernetes-cloud-mysql-backup:test
          # Fetch backup file from GCS
          echo "Fetching database backup..."
          gsutil cp gs://kubernetes-cloud-mysql-backup-github-testing/${{ github.sha }}/world.sql /tmp/world.sql
          # Compare the database backups, diff will exit with 1 if the files do not match causing the workflow to fail
          echo "Comparing database backup to known good database..."
          diff tests/db/world.sql /tmp/world.sql